image:
  # from https://bitbucket.org/persgroep/selectives-bitbucket-pipeline-image
  name: 202994661477.dkr.ecr.eu-west-1.amazonaws.com/sel-bitbucket-pipeline-image-repo:latest

  aws:
    access-key: $AWS_ACCESS_KEY_ID
    secret-key: $AWS_SECRET_ACCESS_KEY

pipelines:
  default:
    - step:
        name: Install
        script:
          - npm-setup-artifactory.sh $ARTIFACTORY_USER $ARTIFACTORY_PASSWORD
          - npm ci
    - step:
        name: Transform Figma Tokens
        caches:
          - node
        script:
          - npm run transform
    - step:
        name: Build Style Dictionary
        script:
          - npm-setup-artifactory.sh $ARTIFACTORY_USER $ARTIFACTORY_PASSWORD
          - npm run build:style-dictionary
        caches:
          - node
