image:
  # from https://bitbucket.org/persgroep/selectives-bitbucket-pipeline-image
  name: 202994661477.dkr.ecr.eu-west-1.amazonaws.com/sel-bitbucket-pipeline-image-repo:latest

  aws:
    access-key: $AWS_ACCESS_KEY_ID
    secret-key: $AWS_SECRET_ACCESS_KEY

definitions:
  services:
    docker:
      memory: 1024

  steps:
    - step: &Push-to-GitHub
        name: Push code changes to GitHub
        services:
          - docker
        caches:
          - docker
        script:
          - git remote add github "git@github.com:roeland-dpg/dnr-design-tokens.git"
          - git checkout $BITBUCKET_BRANCH
          - git pull
          - git push github $BITBUCKET_BRANCH

pipelines:
  default:
    - step: *Push-to-GitHub
    - step:
        name: Transform and Build
        script:
          - npm-setup-artifactory.sh $ARTIFACTORY_USER $ARTIFACTORY_PASSWORD
          - npm ci
          - npm run build
