name: 'Push to bitbucket'

on:
  push

jobs:
  check-links:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0 # <-- clone with complete history
        - name: Push
          uses: heussd/mirror-to-bitbucket-github-action@v2
          with:
            username: bitbucket-pipeline
            repository: dnr-design-tokens
            password: ${{ secrets.BB_REPO_PASSWORD }}
